Rector\Doctrine\Tests\CodeQuality\Rector\Class_\YamlToAttributeDoctrineMappingRector\Fixture\IdMapping:
  id:
    id:
      type: integer
      generator:
        strategy: auto

Rector\Doctrine\Tests\CodeQuality\Rector\Class_\YamlToAttributeDoctrineMappingRector\Fixture\IdMappingConstructor:
    id:
        id:
            type: integer
            generator:
                strategy: auto
