Rector\Doctrine\Tests\CodeQuality\Rector\Class_\YamlToAttributeDoctrineMappingRector\Fixture\ManyToOneJoinColumn:
    manyToOne:
        anotherObject:
            targetEntity: App\SomeTargetEntity
            joinColumns:
                only_column_name:
                    referencedColumnName: some_id
        simpleObject:
            targetEntity: App\SomeTargetEntity
            joinColumns:
                first_column_name:
                    referencedColumnName: some_id
                second_column_name:
                    referencedColumnName: some_id
