Rector\Doctrine\Tests\CodeQuality\Rector\Class_\YamlToAttributeDoctrineMappingRector\Fixture\SomeOrderBy:
  type: entity

  oneToMany:
      categoryEvents:
          targetEntity: App\SomeTargetEntity
          orderBy:
              id: ASC
