Rector\Doctrine\Tests\CodeQuality\Rector\Class_\YamlToAnnotationsDoctrineMappingRector\Fixture\TimestampableGedmo:
  gedmo:
  fields:
    created:
      gedmo:
        timestampable:
          on: create
    updated:
      gedmo:
        timestampable:
          on: update
          field:
            - another_field
            - next_field
