<?php

use Doctrine\DBAL\Types\Type;

Type::TARRAY;
Type::SIMPLE_ARRAY;
Type::JSON_ARRAY;
Type::JSON;
Type::BIGINT;
Type::BOOLEAN;
Type::DATETIME;
Type::DATETIME_IMMUTABLE;
Type::DATETIMETZ;
Type::DATETIMETZ_IMMUTABLE;
Type::DATE;
Type::DATE_IMMUTABLE;
Type::TIME;
Type::TIME_IMMUTABLE;
Type::DECIMAL;
Type::INTEGER;
Type::OBJECT;
Type::SMALLINT;
Type::STRING;
Type::TEXT;
Type::BINARY;
Type::BLOB;
Type::FLOAT;
Type::GUID;
Type::DATEINTERVAL;
?>
-----
<?php

use Doctrine\DBAL\Types\Type;

\Doctrine\DBAL\Types\Types::ARRAY;
\Doctrine\DBAL\Types\Types::SIMPLE_ARRAY;
\Doctrine\DBAL\Types\Types::JSON_ARRAY;
\Doctrine\DBAL\Types\Types::JSON;
\Doctrine\DBAL\Types\Types::BIGINT;
\Doctrine\DBAL\Types\Types::BOOLEAN;
\Doctrine\DBAL\Types\Types::DATETIME_MUTABLE;
\Doctrine\DBAL\Types\Types::DATETIME_IMMUTABLE;
\Doctrine\DBAL\Types\Types::DATETIMETZ_MUTABLE;
\Doctrine\DBAL\Types\Types::DATETIMETZ_IMMUTABLE;
\Doctrine\DBAL\Types\Types::DATE_MUTABLE;
\Doctrine\DBAL\Types\Types::DATE_IMMUTABLE;
\Doctrine\DBAL\Types\Types::TIME_MUTABLE;
\Doctrine\DBAL\Types\Types::TIME_IMMUTABLE;
\Doctrine\DBAL\Types\Types::DECIMAL;
\Doctrine\DBAL\Types\Types::INTEGER;
\Doctrine\DBAL\Types\Types::OBJECT;
\Doctrine\DBAL\Types\Types::SMALLINT;
\Doctrine\DBAL\Types\Types::STRING;
\Doctrine\DBAL\Types\Types::TEXT;
\Doctrine\DBAL\Types\Types::BINARY;
\Doctrine\DBAL\Types\Types::BLOB;
\Doctrine\DBAL\Types\Types::FLOAT;
\Doctrine\DBAL\Types\Types::GUID;
\Doctrine\DBAL\Types\Types::DATEINTERVAL;
?>
