name: Code Analysis

on:
    pull_request: null
    push:
        branches:
            - main

jobs:
    code_analysis:
        uses: rectorphp/reusable-workflows/.github/workflows/code_analysis.yaml@main
